version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_licorera
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: licorera
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d licorera"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    build: .
    container_name: nest_api_licorera
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: licorera
      JWT_SECRET: tu_secreto_muy_largo_y_seguro_cambiame
      JWT_EXPIRATION: 7d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
